//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace cheNgonNhatTheGioi.Module.BusinessObjects.classChe
{

    public partial class DanhMuc : XPObject
    {
        short fmadanhmuc;
        public short madanhmuc
        {
            get { return fmadanhmuc; }
            set { SetPropertyValue<short>(nameof(madanhmuc), ref fmadanhmuc, value); }
        }
        string ftendanhmuc;
        public string tendanhmuc
        {
            get { return ftendanhmuc; }
            set { SetPropertyValue<string>(nameof(tendanhmuc), ref ftendanhmuc, value); }
        }
        [Association(@"SanPhamReferencesDanhMuc")]
        public XPCollection<SanPham> SanPhams { get { return GetCollection<SanPham>(nameof(SanPhams)); } }
    }

}
