//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace cheNgonNhatTheGioi.Module.BusinessObjects.classChe
{

    public partial class DonHang : XPObject
    {
        short fmadonhang;
        public short madonhang
        {
            get { return fmadonhang; }
            set { SetPropertyValue<short>(nameof(madonhang), ref fmadonhang, value); }
        }
        KhachHang ftenkhachhang;
        [Association(@"DonHangReferencesKhachHang")]
        public KhachHang tenkhachhang
        {
            get { return ftenkhachhang; }
            set { SetPropertyValue<KhachHang>(nameof(tenkhachhang), ref ftenkhachhang, value); }
        }
        string fsdt;
        public string sdt
        {
            get { return fsdt; }
            set { SetPropertyValue<string>(nameof(sdt), ref fsdt, value); }
        }
        string fmota;
        public string mota
        {
            get { return fmota; }
            set { SetPropertyValue<string>(nameof(mota), ref fmota, value); }
        }
        string femailKh;
        public string emailKh
        {
            get { return femailKh; }
            set { SetPropertyValue<string>(nameof(emailKh), ref femailKh, value); }
        }
        string fdiachi;
        public string diachi
        {
            get { return fdiachi; }
            set { SetPropertyValue<string>(nameof(diachi), ref fdiachi, value); }
        }
        string ftrangthai;
        public string trangthai
        {
            get { return ftrangthai; }
            set { SetPropertyValue<string>(nameof(trangthai), ref ftrangthai, value); }
        }
        short fsoluong;
        public short soluong
        {
            get { return fsoluong; }
            set { SetPropertyValue<short>(nameof(soluong), ref fsoluong, value); }
        }
        decimal ftongtien;
        public decimal tongtien
        {
            get { return ftongtien; }
            set { SetPropertyValue<decimal>(nameof(tongtien), ref ftongtien, value); }
        }
        [Association(@"OdersReferencesDonHang")]
        public XPCollection<Oders> OdersCollection { get { return GetCollection<Oders>(nameof(OdersCollection)); } }
        [Association(@"ThanhToanReferencesDonHang")]
        public XPCollection<ThanhToan> ThanhToans { get { return GetCollection<ThanhToan>(nameof(ThanhToans)); } }
    }

}
