//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace cheNgonNhatTheGioi.Module.BusinessObjects.classChe
{

    public partial class KhachHang : XPObject
    {
        short fmakh;
        public short makh
        {
            get { return fmakh; }
            set { SetPropertyValue<short>(nameof(makh), ref fmakh, value); }
        }
        string ftenkh;
        public string tenkh
        {
            get { return ftenkh; }
            set { SetPropertyValue<string>(nameof(tenkh), ref ftenkh, value); }
        }
        string fsdt;
        public string sdt
        {
            get { return fsdt; }
            set { SetPropertyValue<string>(nameof(sdt), ref fsdt, value); }
        }
        string femailkh;
        public string emailkh
        {
            get { return femailkh; }
            set { SetPropertyValue<string>(nameof(emailkh), ref femailkh, value); }
        }
        string fdiachi;
        public string diachi
        {
            get { return fdiachi; }
            set { SetPropertyValue<string>(nameof(diachi), ref fdiachi, value); }
        }
        [Association(@"DonHangReferencesKhachHang")]
        public XPCollection<DonHang> DonHangs { get { return GetCollection<DonHang>(nameof(DonHangs)); } }
    }

}
