//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace cheNgonNhatTheGioi.Module.BusinessObjects.classChe
{

    public partial class NhaCungCap : XPObject
    {
        short fmancc;
        public short mancc
        {
            get { return fmancc; }
            set { SetPropertyValue<short>(nameof(mancc), ref fmancc, value); }
        }
        string ftenncc;
        public string tenncc
        {
            get { return ftenncc; }
            set { SetPropertyValue<string>(nameof(tenncc), ref ftenncc, value); }
        }
        string fdiachi;
        public string diachi
        {
            get { return fdiachi; }
            set { SetPropertyValue<string>(nameof(diachi), ref fdiachi, value); }
        }
        string fsdt;
        public string sdt
        {
            get { return fsdt; }
            set { SetPropertyValue<string>(nameof(sdt), ref fsdt, value); }
        }
        string femail;
        public string email
        {
            get { return femail; }
            set { SetPropertyValue<string>(nameof(email), ref femail, value); }
        }
        [Association(@"SanPhamReferencesNhaCungCap")]
        public XPCollection<SanPham> SanPhams { get { return GetCollection<SanPham>(nameof(SanPhams)); } }
    }

}
