//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace cheNgonNhatTheGioi.Module.BusinessObjects.classChe
{

    public partial class Oders : XPObject
    {
        DonHang fmadonhang;
        [Association(@"OdersReferencesDonHang")]
        public DonHang madonhang
        {
            get { return fmadonhang; }
            set { SetPropertyValue<DonHang>(nameof(madonhang), ref fmadonhang, value); }
        }
        SanPham fmasp;
        [Association(@"OdersReferencesSanPham")]
        public SanPham masp
        {
            get { return fmasp; }
            set { SetPropertyValue<SanPham>(nameof(masp), ref fmasp, value); }
        }
        short fsoluong;
        public short soluong
        {
            get { return fsoluong; }
            set { SetPropertyValue<short>(nameof(soluong), ref fsoluong, value); }
        }
    }

}
