//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace cheNgonNhatTheGioi.Module.BusinessObjects.classChe
{

    public partial class SanPham : XPObject
    {
        short fmasp;
        public short masp
        {
            get { return fmasp; }
            set { SetPropertyValue<short>(nameof(masp), ref fmasp, value); }
        }
        string ftensp;
        public string tensp
        {
            get { return ftensp; }
            set { SetPropertyValue<string>(nameof(tensp), ref ftensp, value); }
        }
        DanhMuc fid_dm;
        [Association(@"SanPhamReferencesDanhMuc")]
        public DanhMuc id_dm
        {
            get { return fid_dm; }
            set { SetPropertyValue<DanhMuc>(nameof(id_dm), ref fid_dm, value); }
        }
        string fmotasp;
        public string motasp
        {
            get { return fmotasp; }
            set { SetPropertyValue<string>(nameof(motasp), ref fmotasp, value); }
        }
        string fchitietsp;
        public string chitietsp
        {
            get { return fchitietsp; }
            set { SetPropertyValue<string>(nameof(chitietsp), ref fchitietsp, value); }
        }
        string fanhsp;
        public string anhsp
        {
            get { return fanhsp; }
            set { SetPropertyValue<string>(nameof(anhsp), ref fanhsp, value); }
        }
        decimal fgiasp;
        public decimal giasp
        {
            get { return fgiasp; }
            set { SetPropertyValue<decimal>(nameof(giasp), ref fgiasp, value); }
        }
        string fdvt;
        public string dvt
        {
            get { return fdvt; }
            set { SetPropertyValue<string>(nameof(dvt), ref fdvt, value); }
        }
        NhaCungCap fnhasanxuat;
        [Association(@"SanPhamReferencesNhaCungCap")]
        public NhaCungCap nhasanxuat
        {
            get { return fnhasanxuat; }
            set { SetPropertyValue<NhaCungCap>(nameof(nhasanxuat), ref fnhasanxuat, value); }
        }
        DateTime fngaydangsp;
        public DateTime ngaydangsp
        {
            get { return fngaydangsp; }
            set { SetPropertyValue<DateTime>(nameof(ngaydangsp), ref fngaydangsp, value); }
        }
        [Association(@"OdersReferencesSanPham")]
        public XPCollection<Oders> OdersCollection { get { return GetCollection<Oders>(nameof(OdersCollection)); } }
    }

}
