//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace cheNgonNhatTheGioi.Module.BusinessObjects.classChe
{

    public partial class ThanhToan : XPObject
    {
        short fmathanhtoan;
        public short mathanhtoan
        {
            get { return fmathanhtoan; }
            set { SetPropertyValue<short>(nameof(mathanhtoan), ref fmathanhtoan, value); }
        }
        DonHang fmadonhang;
        [Association(@"ThanhToanReferencesDonHang")]
        public DonHang madonhang
        {
            get { return fmadonhang; }
            set { SetPropertyValue<DonHang>(nameof(madonhang), ref fmadonhang, value); }
        }
        decimal fsotien;
        public decimal sotien
        {
            get { return fsotien; }
            set { SetPropertyValue<decimal>(nameof(sotien), ref fsotien, value); }
        }
        DateTime fthoigian;
        public DateTime thoigian
        {
            get { return fthoigian; }
            set { SetPropertyValue<DateTime>(nameof(thoigian), ref fthoigian, value); }
        }
        string fptthanhtoan;
        public string ptthanhtoan
        {
            get { return fptthanhtoan; }
            set { SetPropertyValue<string>(nameof(ptthanhtoan), ref fptthanhtoan, value); }
        }
    }

}
